# Dockerfile.web
FROM node:20.11.1-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

EXPOSE ${PORT}

RUN ls -al

# Command to run the application
CMD ["sh", "-c", "npm run deploy:docker-compose"]
