services:
  app: 
    image: node:20.11.1-alpine
    command: sh -c "npm run deploy:docker-compose"
    ports:
      - 127.0.0.1:${APP_SERVER_PORT_INNER}:${APP_SERVER_PORT_OUTER}
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - APP_SQL_URL=${APP_SQL_URL}
      - APP_SERVER_PORT_INNER=${APP_SERVER_PORT_INNER}
      - APP_SERVER_URL=${APP_SERVER_URL}
    depends_on:
      - db

  # Setup PostgreSQL database container
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres
    restart: always
    user: postgres
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=${APP_SQL_USER}
      - POSTGRES_PASSWORD=${APP_SQL_PASSWORD}
      - POSTGRES_DB=${APP_SQL_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d tokens_db -U tokens_root"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
    
  # Setup simple SQL client in order to check the values in browser
  adminer: 
    image: adminer
    restart: always
    depends_on:
      - db
    ports: 
      - 8080:8080

  
